title:   Olha Priadko
logo: <img src="images/profile pic.png?raw=true"/>
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Dynamic data analyst, adept at delivering innovative technical solutions to improve customer experiences. Skilled in utilizing SQL, Python, and Power BI for automating dashboards and streamlining processes. Proficient in interpreting behavioral data and identifying business gaps, providing clear insights to stakeholders.
  <br><br>
  <a href="https://www.linkedin.com/in/olha-priadko-618496296/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/olha.priadko/vizzes">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/olhapriadko/Business-Analyst-Portfolio-Olha-Priadko-13e5978a405348d2ae1e99c8e440681e?pvs=4">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
